// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQIOqxNOqBpi8cfKrxwnPfftfjchJK1eI',
    appId: '1:691645205679:web:1264575e17df590dc1985a',
    messagingSenderId: '691645205679',
    projectId: 'spotify-fd906',
    authDomain: 'spotify-fd906.firebaseapp.com',
    storageBucket: 'spotify-fd906.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNJ58oWB3cXr_bAWlTEpcwctKITL0eTtc',
    appId: '1:691645205679:android:10aee9f3e245f541c1985a',
    messagingSenderId: '691645205679',
    projectId: 'spotify-fd906',
    storageBucket: 'spotify-fd906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATtUWauEpTaX4mhcPcDQpqw1MkUqL5pXg',
    appId: '1:691645205679:ios:00ac9bf63d825223c1985a',
    messagingSenderId: '691645205679',
    projectId: 'spotify-fd906',
    storageBucket: 'spotify-fd906.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATtUWauEpTaX4mhcPcDQpqw1MkUqL5pXg',
    appId: '1:691645205679:ios:00ac9bf63d825223c1985a',
    messagingSenderId: '691645205679',
    projectId: 'spotify-fd906',
    storageBucket: 'spotify-fd906.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQIOqxNOqBpi8cfKrxwnPfftfjchJK1eI',
    appId: '1:691645205679:web:8777f3838f4efe3ec1985a',
    messagingSenderId: '691645205679',
    projectId: 'spotify-fd906',
    authDomain: 'spotify-fd906.firebaseapp.com',
    storageBucket: 'spotify-fd906.appspot.com',
  );
}
